[package]
name = "rustc_ast_pretty"
version = "0.0.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
tracing = "0.1"
latinoc_span = { path = "../latinoc_span" }
latinoc_ast = { path = "../latinoc_ast" }
